version: "3.7"
services:
  node:
    build: .
    init: true
    restart: always
    environment:
      AABANK_TOKEN: "Your Token"
    volumes:
      - ./db:/app/db
    ports:
      - "9989:9989"
